"""empty message

Revision ID: 2e2bd9b00375
Revises: ca8be7da0ed7
Create Date: 2016-08-27 13:28:33.194908

"""

# revision identifiers, used by Alembic.
revision = '2e2bd9b00375'
down_revision = 'ca8be7da0ed7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('cartegory', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    ### end Alembic commands ###
