"""empty message

Revision ID: 96aedd1a790d
Revises: 2e2bd9b00375
Create Date: 2016-08-27 18:30:26.128947

"""

# revision identifiers, used by Alembic.
revision = '96aedd1a790d'
down_revision = '2e2bd9b00375'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('form', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forms')
    ### end Alembic commands ###
