"""empty message

Revision ID: c596990cbf58
Revises: 96aedd1a790d
Create Date: 2016-10-23 21:02:29.021640

"""

# revision identifiers, used by Alembic.
revision = 'c596990cbf58'
down_revision = '96aedd1a790d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('code', sa.String(length=100), nullable=True))
    op.add_column('marks', sa.Column('form', sa.String(length=100), nullable=True))
    op.add_column('marks', sa.Column('grade', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marks', 'grade')
    op.drop_column('marks', 'form')
    op.drop_column('marks', 'code')
    ### end Alembic commands ###
