"""empty message

Revision ID: ca8be7da0ed7
Revises: None
Create Date: 2016-08-21 22:55:52.289622

"""

# revision identifiers, used by Alembic.
revision = 'ca8be7da0ed7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('regnumber', sa.String(length=100), nullable=True),
    sa.Column('fullname', sa.String(length=100), nullable=True),
    sa.Column('term', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=100), nullable=True),
    sa.Column('merit', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('students',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('middlename', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('regdate', sa.String(length=20), nullable=True),
    sa.Column('regnumber', sa.String(length=10), nullable=True),
    sa.Column('form', sa.String(length=20), nullable=True),
    sa.Column('stream', sa.String(length=20), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('pwdhash', sa.String(length=54), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('students')
    op.drop_table('marks')
    ### end Alembic commands ###
